import 'package:floor/floor.dart';
import 'package:flutter/rendering.dart';

//Here, we are saying to floor that this is a class that defines an entity
@Entity (primaryKeys: ['id']) 
class Day_infos {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  //@PrimaryKey(autoGenerate: true)
  final int? id; 

  //When the steps occured
  final DateTime dateTime;

  final double d_steps;

  final double sleep_minutes;

  //Default constructor
  Day_infos(this.id, this.dateTime, this.d_steps, this.sleep_minutes);
  
}//Meal