import 'package:floor/floor.dart';
import 'package:flutter/rendering.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Day_steps {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id; 

  
  final double d_steps;

  //When the steps occured
  final DateTime dateTime;


  //Default constructor
  Day_steps(this.id, this.d_steps, this.dateTime);
  
}//Meal