import 'package:floor/floor.dart';
import 'package:flutter/rendering.dart';

//Here, we are saying to floor that this is a class that defines an entity
@Entity (primaryKeys: ['id']) 
class Yesterday_sleep {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  //@PrimaryKey(autoGenerate: true)
  final int? id; 

  final DateTime dateTime;
  final String level;
  final DateTime entryDateTime;

  //Default constructor
  Yesterday_sleep(this.id, this.dateTime, this.level, this.entryDateTime);
  
}//Meal